name: cover
on:
  push: branches:[main]
jobs:
  cover_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn add
      - uses: ArtiomTr/jest-coverage-report-action@v2
