name: tinh tong cac so
on:
  push:
    branches: [main]
jobs:
  tinh-tong:
    runs-on: ubuntu-latest
    steps:
      - run: echo helo tinh tong
      - run: echo "TODAY=$(date +%d/%m/%y)" >> $GITHUB_ENV
      - run: echo Today is $TODAY
